package cl.movistar.tracking.hibernate;
// Generated 23-06-2014 06:08:01 PM by Hibernate Tools 3.2.1.GA



/**
 * AccionNegocio generated by hbm2java
 */
public class AccionNegocio  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private String tipo;
     private String data;

    public AccionNegocio() {
    }

	
    public AccionNegocio(int id, String nombre, String descripcion, String tipo) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.tipo = tipo;
    }
    public AccionNegocio(int id, String nombre, String descripcion, String tipo, String data) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.data = data;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }




}


