package cl.movistar.tracking.hibernate;
// Generated 23-06-2014 06:08:01 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MovimientosTracking generated by hbm2java
 */
public class MovimientosTracking  implements java.io.Serializable {


     private int id;
     private Integer numeroCelular;
     private Integer numeroAbonado;
     private Integer codigoCliente;
     private Integer cicloFacturacion;
     private String codigoOferta;
     private String nombreOferta;
     private Date fechaContratacion;
     private Date fechaActivacion;
     private Date fechaNotificacion;
     private Integer canal;
     private Integer subCanal;
     private Integer estado;
     private String agencia;
     private String codigoVendedor;
     private Integer precio;
     private Integer descuento;
     private Integer puntosUtilizados;
     private Integer idTracking;
     private Integer idEventoTracking;
     private String usuario;

    public MovimientosTracking() {
    }

	
    public MovimientosTracking(int id) {
        this.id = id;
    }
    public MovimientosTracking(int id, Integer numeroCelular, Integer numeroAbonado, Integer codigoCliente, Integer cicloFacturacion, String codigoOferta, String nombreOferta, Date fechaContratacion, Date fechaActivacion, Date fechaNotificacion, Integer canal, Integer subCanal, Integer estado, String agencia, String codigoVendedor, Integer precio, Integer descuento, Integer puntosUtilizados, Integer idTracking, Integer idEventoTracking, String usuario) {
       this.id = id;
       this.numeroCelular = numeroCelular;
       this.numeroAbonado = numeroAbonado;
       this.codigoCliente = codigoCliente;
       this.cicloFacturacion = cicloFacturacion;
       this.codigoOferta = codigoOferta;
       this.nombreOferta = nombreOferta;
       this.fechaContratacion = fechaContratacion;
       this.fechaActivacion = fechaActivacion;
       this.fechaNotificacion = fechaNotificacion;
       this.canal = canal;
       this.subCanal = subCanal;
       this.estado = estado;
       this.agencia = agencia;
       this.codigoVendedor = codigoVendedor;
       this.precio = precio;
       this.descuento = descuento;
       this.puntosUtilizados = puntosUtilizados;
       this.idTracking = idTracking;
       this.idEventoTracking = idEventoTracking;
       this.usuario = usuario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getNumeroCelular() {
        return this.numeroCelular;
    }
    
    public void setNumeroCelular(Integer numeroCelular) {
        this.numeroCelular = numeroCelular;
    }
    public Integer getNumeroAbonado() {
        return this.numeroAbonado;
    }
    
    public void setNumeroAbonado(Integer numeroAbonado) {
        this.numeroAbonado = numeroAbonado;
    }
    public Integer getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(Integer codigoCliente) {
        this.codigoCliente = codigoCliente;
    }
    public Integer getCicloFacturacion() {
        return this.cicloFacturacion;
    }
    
    public void setCicloFacturacion(Integer cicloFacturacion) {
        this.cicloFacturacion = cicloFacturacion;
    }
    public String getCodigoOferta() {
        return this.codigoOferta;
    }
    
    public void setCodigoOferta(String codigoOferta) {
        this.codigoOferta = codigoOferta;
    }
    public String getNombreOferta() {
        return this.nombreOferta;
    }
    
    public void setNombreOferta(String nombreOferta) {
        this.nombreOferta = nombreOferta;
    }
    public Date getFechaContratacion() {
        return this.fechaContratacion;
    }
    
    public void setFechaContratacion(Date fechaContratacion) {
        this.fechaContratacion = fechaContratacion;
    }
    public Date getFechaActivacion() {
        return this.fechaActivacion;
    }
    
    public void setFechaActivacion(Date fechaActivacion) {
        this.fechaActivacion = fechaActivacion;
    }
    public Date getFechaNotificacion() {
        return this.fechaNotificacion;
    }
    
    public void setFechaNotificacion(Date fechaNotificacion) {
        this.fechaNotificacion = fechaNotificacion;
    }
    public Integer getCanal() {
        return this.canal;
    }
    
    public void setCanal(Integer canal) {
        this.canal = canal;
    }
    public Integer getSubCanal() {
        return this.subCanal;
    }
    
    public void setSubCanal(Integer subCanal) {
        this.subCanal = subCanal;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
   
    public String getCodigoVendedor() {
        return this.codigoVendedor;
    }
    
    public void setCodigoVendedor(String codigoVendedor) {
        this.codigoVendedor = codigoVendedor;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public Integer getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Integer descuento) {
        this.descuento = descuento;
    }
    public Integer getPuntosUtilizados() {
        return this.puntosUtilizados;
    }
    
    public void setPuntosUtilizados(Integer puntosUtilizados) {
        this.puntosUtilizados = puntosUtilizados;
    }
    public Integer getIdTracking() {
        return this.idTracking;
    }
    
    public void setIdTracking(Integer idTracking) {
        this.idTracking = idTracking;
    }
    public Integer getIdEventoTracking() {
        return this.idEventoTracking;
    }
    
    public void setIdEventoTracking(Integer idEventoTracking) {
        this.idEventoTracking = idEventoTracking;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    /**
     * @return the agencia
     */
    public String getAgencia() {
        return agencia;
    }

    /**
     * @param agencia the agencia to set
     */
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }




}


