package cl.movistar.tracking.hibernate;
// Generated 23-06-2014 06:08:01 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * VentaBolsa generated by hbm2java
 */
public class VentaBolsa  implements java.io.Serializable {


     private int id;
     private int numeroCelular;
     private int numeroAbonado;
     private int codigoCliente;
     private int cicloFacturacion;
     private String codigoOferta;
     private String nombreOferta;
     private Date fechaContratacion;
     private Date fechaActivacion;
     private Date fechaNotificacion;
     private int canal;
     private Integer subCanal;
     private int estado;
     private String agencia;
     private String codigoVendedor;
     private int precio;
     private int descuento;
     private int puntosUtilizados;
     private int idTracking;
     private String usuario;

    public VentaBolsa() {
    }

	
    public VentaBolsa(int id, int numeroCelular, int numeroAbonado, int codigoCliente, int cicloFacturacion, String codigoOferta, String nombreOferta, Date fechaContratacion, int canal, int estado, String codigoVendedor, int precio, int descuento, int puntosUtilizados, int idTracking) {
        this.id = id;
        this.numeroCelular = numeroCelular;
        this.numeroAbonado = numeroAbonado;
        this.codigoCliente = codigoCliente;
        this.cicloFacturacion = cicloFacturacion;
        this.codigoOferta = codigoOferta;
        this.nombreOferta = nombreOferta;
        this.fechaContratacion = fechaContratacion;
        this.canal = canal;
        this.estado = estado;
        this.codigoVendedor = codigoVendedor;
        this.precio = precio;
        this.descuento = descuento;
        this.puntosUtilizados = puntosUtilizados;
        this.idTracking = idTracking;
    }
    public VentaBolsa(int id, int numeroCelular, int numeroAbonado, int codigoCliente, int cicloFacturacion, String codigoOferta, String nombreOferta, Date fechaContratacion, Date fechaActivacion, Date fechaNotificacion, int canal, Integer subCanal, int estado, String agencia, String codigoVendedor, int precio, int descuento, int puntosUtilizados, int idTracking, String usuario) {
       this.id = id;
       this.numeroCelular = numeroCelular;
       this.numeroAbonado = numeroAbonado;
       this.codigoCliente = codigoCliente;
       this.cicloFacturacion = cicloFacturacion;
       this.codigoOferta = codigoOferta;
       this.nombreOferta = nombreOferta;
       this.fechaContratacion = fechaContratacion;
       this.fechaActivacion = fechaActivacion;
       this.fechaNotificacion = fechaNotificacion;
       this.canal = canal;
       this.subCanal = subCanal;
       this.estado = estado;
       this.agencia = agencia;
       this.codigoVendedor = codigoVendedor;
       this.precio = precio;
       this.descuento = descuento;
       this.puntosUtilizados = puntosUtilizados;
       this.idTracking = idTracking;
       this.usuario = usuario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getNumeroCelular() {
        return this.numeroCelular;
    }
    
    public void setNumeroCelular(int numeroCelular) {
        this.numeroCelular = numeroCelular;
    }
    public int getNumeroAbonado() {
        return this.numeroAbonado;
    }
    
    public void setNumeroAbonado(int numeroAbonado) {
        this.numeroAbonado = numeroAbonado;
    }
    public int getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(int codigoCliente) {
        this.codigoCliente = codigoCliente;
    }
    public int getCicloFacturacion() {
        return this.cicloFacturacion;
    }
    
    public void setCicloFacturacion(int cicloFacturacion) {
        this.cicloFacturacion = cicloFacturacion;
    }
    public String getCodigoOferta() {
        return this.codigoOferta;
    }
    
    public void setCodigoOferta(String codigoOferta) {
        this.codigoOferta = codigoOferta;
    }
    public String getNombreOferta() {
        return this.nombreOferta;
    }
    
    public void setNombreOferta(String nombreOferta) {
        this.nombreOferta = nombreOferta;
    }
    public Date getFechaContratacion() {
        return this.fechaContratacion;
    }
    
    public void setFechaContratacion(Date fechaContratacion) {
        this.fechaContratacion = fechaContratacion;
    }
    public Date getFechaActivacion() {
        return this.fechaActivacion;
    }
    
    public void setFechaActivacion(Date fechaActivacion) {
        this.fechaActivacion = fechaActivacion;
    }
    public Date getFechaNotificacion() {
        return this.fechaNotificacion;
    }
    
    public void setFechaNotificacion(Date fechaNotificacion) {
        this.fechaNotificacion = fechaNotificacion;
    }
    public int getCanal() {
        return this.canal;
    }
    
    public void setCanal(int canal) {
        this.canal = canal;
    }
    public Integer getSubCanal() {
        return this.subCanal;
    }
    
    public void setSubCanal(Integer subCanal) {
        this.subCanal = subCanal;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }
    public String getCodigoVendedor() {
        return this.codigoVendedor;
    }
    
    public void setCodigoVendedor(String codigoVendedor) {
        this.codigoVendedor = codigoVendedor;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public int getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(int descuento) {
        this.descuento = descuento;
    }
    public int getPuntosUtilizados() {
        return this.puntosUtilizados;
    }
    
    public void setPuntosUtilizados(int puntosUtilizados) {
        this.puntosUtilizados = puntosUtilizados;
    }
    public int getIdTracking() {
        return this.idTracking;
    }
    
    public void setIdTracking(int idTracking) {
        this.idTracking = idTracking;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }




}


