package cl.telefonica.tracking.hibernate.dto;
// Generated 09-06-2014 12:28:10 PM by Hibernate Tools 3.2.1.GA



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private String rut;
     private String contrasena;

    public Usuarios() {
    }

    public Usuarios(int codigo, String nombre, String rut, String contrasena) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.rut = rut;
       this.contrasena = contrasena;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }




}


